using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DoStatement
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>

    public partial class MainWindow : Window
    {

        public MainWindow()
        {
            InitializeComponent();
        }

        private void showStepsClick(object sender, RoutedEventArgs e)
        {
            int amount = int.Parse(number.Text);  // to obtain the number to be octal-ed..
            steps.Text = "";  // to clear the steps box
            string current = ""; // string that will be used to store the digits generated by the division by 8.
            string current2String = ""; // using the more direct command, that basically calls the 2 commands further down that convert the number into a character.

            do
            {
                int nextDigit = amount % 8;
                amount /= 8;
                int digitCode = '0' + nextDigit;  //Characters have an unique code according to the character set used by the OS. For Windows, '0' has integer value 48.
                char digit = Convert.ToChar(digitCode); // Convert.ToChar method takes an integer holding a character and returns the corresponding character.
                current = digit + current;
                current2String = nextDigit.ToString() + current2String;
                steps.Text += current + "\n";
                steps.Text += current2String + "\n";
            } while (amount != 0);

        }
    }
}